import type { GitHubService } from "../ports/github-service.js";
import { FatalSystemError } from "../self-monitor/index.js";
import { analyzeError } from "./analyzer.js";
import { PatchGenerator } from "./patch-generator.js";
import { SafeDeployer } from "./deployer.js";
import { Validator } from "./validator.js";
import type { Patch, RollbackSnapshot, RootCauseAnalysis } from "./types.js";

export interface SelfEvolutionDeps {
	github: GitHubService;
	repoPath: string;
	selfReportRepo: { owner: string; repo: string };
}

export class SelfEvolutionEngine {
	private readonly patchGenerator = new PatchGenerator();
	private readonly deployer = new SafeDeployer();
	private readonly validator = new Validator();

	constructor(private readonly deps: SelfEvolutionDeps) {}

	async handleError(error: Error): Promise<void> {
		const analysis = analyzeError(error, this.deps.repoPath);
		if (analysis.level !== "code-level") {
			process.stdout.write(`[self-evolution] skipping ${analysis.level} issue: ${analysis.description}\n`);
			return;
		}

		process.stdout.write(`[self-evolution] code-level issue detected: ${analysis.description}\n`);
		const patches: Patch[] = [];
		for (const file of analysis.affectedFiles) {
			try {
				const patch = await this.patchGenerator.generate(file, error.message, error.stack);
				if (patch) {
					patches.push(patch);
					process.stdout.write(`[self-evolution] generated patch for ${file}\n`);
				}
			} catch (genError) {
				process.stdout.write(
					`[self-evolution] patch generation failed for ${file}: ${genError instanceof Error ? genError.message : String(genError)}\n`,
				);
			}
		}

		if (patches.length === 0) {
			process.stdout.write(`[self-evolution] no patches generated\n`);
			await this.fileIssue(analysis, patches, null, null);
			return;
		}

		let snapshot: RollbackSnapshot | undefined;
		let deployError: string | null = null;
		try {
			snapshot = await this.deployPatches(patches);
		} catch (err) {
			deployError = err instanceof Error ? err.message : String(err);
			process.stdout.write(`[self-evolution] deployment failed: ${deployError}\n`);
			await this.fileIssue(analysis, patches, null, deployError);
			return;
		}

		const validation = await this.validator.validate("npm run guardrail:test", this.deps.repoPath);
		if (validation.ok) {
			process.stdout.write(`[self-evolution] validation passed, keeping patches\n`);
			await this.fileIssue(analysis, patches, validation, null);
		} else {
			process.stdout.write(`[self-evolution] validation failed, rolling back\n`);
			if (snapshot) {
				try {
					await this.deployer.rollback(snapshot);
				} catch (rollbackError) {
					process.stdout.write(
						`[self-evolution] rollback failed: ${rollbackError instanceof Error ? rollbackError.message : String(rollbackError)}\n`,
					);
				}
			}
			await this.fileIssue(analysis, patches, validation, null);
		}
	}

	private async deployPatches(patches: Patch[]): Promise<RollbackSnapshot> {
		const allBackups: Record<string, string> = {};
		let timestamp = "";
		for (const patch of patches) {
			const snapshot = await this.deployer.applyPatch(patch);
			timestamp = snapshot.timestamp;
			Object.assign(allBackups, snapshot.backups);
		}
		return { timestamp, backups: allBackups };
	}

	private async fileIssue(
		analysis: RootCauseAnalysis,
		patches: Patch[],
		validation: { ok: boolean; output: string } | null,
		deployError: string | null,
	): Promise<void> {
		const title = `Self-evolution patch: ${analysis.description.slice(0, 80)}`;
		let body = `## Root Cause Analysis\n\n${analysis.description}\n\nAffected files:\n${analysis.affectedFiles.map((f) => `- \`${f}\``).join("\n")}\n\n`;
		if (patches.length > 0) {
			body += `## Proposed Patches\n\n`;
			for (const patch of patches) {
				body += `<details>\n<summary>${patch.filePath}</summary>\n\n\`\`\`diff\n${patch.diff}\n\`\`\`\n\n</details>\n\n`;
			}
		}
		if (validation) {
			body += `## Validation\n\nResult: ${validation.ok ? "PASSED" : "FAILED"}\n\n\`\`\`\n${validation.output.slice(0, 2000)}\n\`\`\`\n\n`;
		}
		if (deployError) {
			body += `## Deployment Error\n\n\`\`\`\n${deployError}\n\`\`\`\n\n`;
		}
		body += `---\n*Generated by Yeetomatic self-evolution engine.*`;
		await this.deps.github.createIssue(
			this.deps.selfReportRepo.owner,
			this.deps.selfReportRepo.repo,
			title,
			body,
			["yeetomatic-self-evolution", "bug"],
		);
	}
}
