import React, { useCallback, useEffect, useMemo, useRef, useState } from "react";
import {
	submitOnboarding,
	verifyGitHubToken,
	generateWebhookSecret,
	listAccessibleRepositories,
	initializeWorkspaces,
} from "../../api/onboarding.js";

export type GithubEventMode = "webhook" | "polling" | "both";

interface WizardState {
	step: number;
	adminUsername: string;
	adminPassword: string;
	githubToken: string;
	githubUsername: string;
	githubUsernameConfirmed: boolean;
	githubEventMode: string;
	githubPollIntervalMs: string;
	webhookSecret: string;
	webhookSecretConfirmed: boolean;
	repositories: Array<{ owner: string; repo: string; fullName: string; selected: boolean }>;
	error: string | null;
}

const STORAGE_KEY = "tars-onboarding-wizard";
const TOTAL_STEPS = 5;

export const EVENT_MODE_OPTIONS: readonly GithubEventMode[] = ["webhook", "polling", "both"];
export const MIN_POLL_INTERVAL_MS = 1000;
export const DEFAULT_POLL_INTERVAL_MS = 60000;

export function isPollingMode(mode: string): boolean {
	return mode === "polling" || mode === "both";
}

export function isValidEventMode(mode: string): boolean {
	return (EVENT_MODE_OPTIONS as readonly string[]).includes(mode);
}

/**
 * Parses a polling interval string into a positive integer of at least
 * MIN_POLL_INTERVAL_MS, or returns null when the value is empty or invalid.
 */
export function parsePollIntervalMs(raw: string): number | null {
	const trimmed = raw.trim();
	if (!/^[0-9]+$/.test(trimmed)) {
		return null;
	}
	const value = Number.parseInt(trimmed, 10);
	if (!Number.isInteger(value) || value < MIN_POLL_INTERVAL_MS) {
		return null;
	}
	return value;
}

function generatePassword(): string {
	const chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*-_+=";
	const array = new Uint8Array(24);
	window.crypto.getRandomValues(array);
	let password = "";
	for (let i = 0; i < array.length; i++) {
		password += chars[array[i] % chars.length];
	}
	return password;
}

function loadState(): WizardState {
	try {
		const raw = localStorage.getItem(STORAGE_KEY);
		if (raw) {
			const parsed = JSON.parse(raw) as WizardState;
			return { ...getDefaultState(), ...parsed, error: null };
		}
	} catch {
		// ignore
	}
	return getDefaultState();
}

function saveState(state: WizardState): void {
	try {
		localStorage.setItem(STORAGE_KEY, JSON.stringify(state));
	} catch {
		// ignore
	}
}

function getDefaultState(): WizardState {
	return {
		step: 1,
		adminUsername: "admin",
		adminPassword: generatePassword(),
		githubToken: "",
		githubUsername: "",
		githubUsernameConfirmed: false,
		githubEventMode: "",
		githubPollIntervalMs: "",
		webhookSecret: "",
		webhookSecretConfirmed: false,
		repositories: [],
		error: null,
	};
}

export function OnboardingWizard({ onComplete }: { onComplete?: () => void }): React.ReactElement {
	const [state, setState] = useState<WizardState>(() => loadState());
	const [loading, setLoading] = useState(false);
	const [done, setDone] = useState(false);

	useEffect(() => {
		saveState(state);
	}, [state]);

	const setError = useCallback((error: string | null) => {
		setState((prev) => ({ ...prev, error }));
	}, []);

	const goToStep = useCallback((step: number) => {
		setState((prev) => ({ ...prev, step: Math.max(1, Math.min(TOTAL_STEPS, step)), error: null }));
	}, []);

	const updateField = useCallback(<K extends keyof WizardState>(key: K, value: WizardState[K]) => {
		setState((prev) => ({ ...prev, [key]: value, error: null }));
	}, []);

	const handleVerifyToken = useCallback(async () => {
		setLoading(true);
		setError(null);
		try {
			const result = await verifyGitHubToken(state.githubToken.trim());
			setState((prev) => ({ ...prev, githubUsername: result.username, githubUsernameConfirmed: true }));
		} catch (err) {
			setError(err instanceof Error ? err.message : String(err));
		} finally {
			setLoading(false);
		}
	}, [state.githubToken, setError]);

	const handleGenerateSecret = useCallback(async () => {
		setLoading(true);
		setError(null);
		try {
			const result = await generateWebhookSecret();
			setState((prev) => ({ ...prev, webhookSecret: result.secret }));
		} catch (err) {
			setError(err instanceof Error ? err.message : String(err));
		} finally {
			setLoading(false);
		}
	}, [setError]);

	const hasAutoGeneratedSecretRef = useRef(false);

	useEffect(() => {
		if (state.step === 4 && !state.webhookSecret && !loading && !hasAutoGeneratedSecretRef.current) {
			hasAutoGeneratedSecretRef.current = true;
			handleGenerateSecret();
		}
	}, [state.step, state.webhookSecret, loading, handleGenerateSecret]);

	const handleFetchRepos = useCallback(async () => {
		setLoading(true);
		setError(null);
		try {
			const result = await listAccessibleRepositories(state.githubToken.trim());
			const repos = result.repositories.map((r) => ({ ...r, selected: true }));
			setState((prev) => ({ ...prev, repositories: repos }));
		} catch (err) {
			setError(err instanceof Error ? err.message : String(err));
		} finally {
			setLoading(false);
		}
	}, [state.githubToken, setError]);

	const toggleRepo = useCallback((index: number) => {
		setState((prev) => {
			const repos = [...prev.repositories];
			repos[index] = { ...repos[index], selected: !repos[index].selected };
			return { ...prev, repositories: repos };
		});
	}, []);

	const setAllReposSelected = useCallback((selected: boolean) => {
		setState((prev) => ({
			...prev,
			repositories: prev.repositories.map((repo) => ({ ...repo, selected })),
		}));
	}, []);

	const handleFinish = useCallback(async () => {
		setLoading(true);
		setError(null);
		try {
			const selectedRepos = state.repositories.filter((r) => r.selected);
			if (selectedRepos.length > 0) {
				await initializeWorkspaces({
					token: state.githubToken.trim(),
					username: state.githubUsername.trim(),
					repos: selectedRepos.map((r) => ({ owner: r.owner, repo: r.repo })),
				});
			}

			const onboardingBody: Record<string, string> = {
				github_token: state.githubToken.trim(),
				github_username: state.githubUsername.trim(),
				webhook_secret: state.webhookSecret.trim(),
				admin_username: state.adminUsername.trim(),
				admin_password: state.adminPassword.trim(),
				github_event_mode: state.githubEventMode,
			};
			if (isPollingMode(state.githubEventMode)) {
				const interval = parsePollIntervalMs(state.githubPollIntervalMs);
				if (interval !== null) {
					onboardingBody.github_poll_interval_ms = String(interval);
				}
			}
			await submitOnboarding(onboardingBody);

			localStorage.removeItem(STORAGE_KEY);
			setDone(true);
			onComplete?.();
		} catch (err) {
			setError(err instanceof Error ? err.message : String(err));
			setLoading(false);
		}
	}, [state, onComplete]);

	const handleCancel = useCallback(() => {
		if (confirm("Are you sure you want to cancel the onboarding? Your progress will be lost.")) {
			localStorage.removeItem(STORAGE_KEY);
			window.location.reload();
		}
	}, []);

	const canGoNext = useMemo(() => {
		switch (state.step) {
			case 1:
				return state.adminUsername.trim().length > 0 && state.adminPassword.trim().length > 0;
			case 2:
				return state.githubToken.trim().length > 0 && state.githubUsernameConfirmed;
			case 3:
				return isEventModeStepValid(state.githubEventMode, state.githubPollIntervalMs);
			case 4:
				return state.webhookSecret.trim().length > 0 && state.webhookSecretConfirmed;
			case 5:
				return true;
			default:
				return false;
		}
	}, [state]);

	if (done) {
		return (
			<div className="onboarding-screen">
				<div className="onboarding-card">
					<h2>Setup Complete</h2>
					<p className="onboarding-subtitle">
						Your settings have been saved and TARS is loading them now.
					</p>
				</div>
			</div>
		);
	}

	return (
		<div className="onboarding-screen">
			<div className="onboarding-card">
				<div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: "0.5rem" }}>
					<h1>Welcome to TARS</h1>
					<span style={{ color: "var(--muted)", fontSize: "0.875rem" }}>Step {state.step} of {TOTAL_STEPS}</span>
				</div>
				<div
					style={{
						display: "flex",
						gap: "0.25rem",
						marginBottom: "1.5rem",
					}}
				>
					{Array.from({ length: TOTAL_STEPS }, (_, i) => (
						<div
							key={i}
							style={{
								flex: 1,
								height: "4px",
								borderRadius: "2px",
								background: i < state.step ? "var(--blue)" : "var(--border)",
								transition: "background 0.2s ease",
							}}
						/>
					))}
				</div>
				<p className="onboarding-subtitle">{getStepSubtitle(state.step)}</p>

				{state.error && <div className="error-banner">{state.error}</div>}

				{state.step === 1 && (
					<StepOneAdminCredentials
						state={state}
						updateField={updateField}
						onGeneratePassword={() => updateField("adminPassword", generatePassword())}
					/>
				)}
				{state.step === 2 && (
					<StepTwoGitHubIntegration
						state={state}
						updateField={updateField}
						onVerifyToken={handleVerifyToken}
						loading={loading}
					/>
				)}
				{state.step === 3 && (
					<StepThreeEventMode
						state={state}
						updateField={updateField}
					/>
				)}
				{state.step === 4 && (
					<StepFourWebhookSecurity
						state={state}
						updateField={updateField}
						onGenerateSecret={handleGenerateSecret}
						loading={loading}
					/>
				)}
				{state.step === 5 && (
					<StepFiveWorkspaceInit
						state={state}
						onFetchRepos={handleFetchRepos}
						onToggleRepo={toggleRepo}
						onSetAllReposSelected={setAllReposSelected}
						onFinish={handleFinish}
						loading={loading}
					/>
				)}

				<div style={{ display: "flex", gap: "0.75rem", marginTop: "1.5rem", justifyContent: "space-between" }}>
					<div style={{ display: "flex", gap: "0.75rem" }}>
						{state.step > 1 && (
							<button
								className="action-btn"
								style={{ background: "var(--surface)", border: "1px solid var(--border)", color: "var(--text)" }}
								type="button"
								onClick={() => goToStep(state.step - 1)}
								disabled={loading}
							>
								Back
							</button>
						)}
						<button
							className="action-btn"
							style={{ background: "var(--surface)", border: "1px solid var(--border)", color: "var(--red)" }}
							type="button"
								onClick={handleCancel}
								disabled={loading}
							>
							Cancel
						</button>
					</div>
					{state.step < TOTAL_STEPS ? (
						<button
							className="action-btn restart"
							type="button"
							onClick={() => goToStep(state.step + 1)}
							disabled={!canGoNext || loading}
						>
							Next
						</button>
					) : (
						<button
							className="action-btn restart"
							type="button"
							onClick={handleFinish}
							disabled={!canGoNext || loading}
						>
							{loading ? "Initializing..." : "Initialize & Finish"}
						</button>
					)}
				</div>
			</div>
		</div>
	);
}

function isEventModeStepValid(mode: string, pollInterval: string): boolean {
	if (!isValidEventMode(mode)) {
		return false;
	}
	if (isPollingMode(mode)) {
		return parsePollIntervalMs(pollInterval) !== null;
	}
	return true;
}

function getStepSubtitle(step: number): string {
	switch (step) {
		case 1:
			return "Set up your admin credentials for the dashboard.";
		case 2:
			return "Connect your GitHub account with a Personal Access Token.";
		case 3:
			return "Choose how TARS receives GitHub events.";
		case 4:
			return "Secure your webhook with a high-entropy secret.";
		case 5:
			return "Initialize workspaces for the repositories you want TARS to manage.";
		default:
			return "";
	}
}

function StepOneAdminCredentials({
	state,
	updateField,
	onGeneratePassword,
}: {
	state: WizardState;
	updateField: <K extends keyof WizardState>(key: K, value: WizardState[K]) => void;
	onGeneratePassword: () => void;
}): React.ReactElement {
	const [showPassword, setShowPassword] = useState(true);

	return (
		<div className="onboarding-form">
			<div className="form-group">
				<label htmlFor="admin_username">Admin Username</label>
				<input
					id="admin_username"
					type="text"
					value={state.adminUsername}
					onChange={(e) => updateField("adminUsername", e.target.value)}
					placeholder="admin"
					required
				/>
				<span className="setting-description">Username for the admin dashboard</span>
			</div>
			<div className="form-group">
				<label htmlFor="admin_password">Admin Password</label>
				<div style={{ display: "flex", gap: "0.5rem" }}>
					<input
						id="admin_password"
						type={showPassword ? "text" : "password"}
						value={state.adminPassword}
						onChange={(e) => updateField("adminPassword", e.target.value)}
						placeholder="password"
						required
						style={{ flex: 1 }}
					/>
					<button
						type="button"
						className="action-btn"
						style={{ background: "var(--surface)", border: "1px solid var(--border)", color: "var(--text)", whiteSpace: "nowrap" }}
						onClick={onGeneratePassword}
					>
						Regenerate
					</button>
				</div>
				<div style={{ display: "flex", alignItems: "center", gap: "0.5rem", marginTop: "0.35rem" }}>
					<label style={{ display: "flex", alignItems: "center", gap: "0.4rem", cursor: "pointer", fontSize: "0.875rem", color: "var(--muted)" }}>
						<input
							type="checkbox"
							checked={showPassword}
							onChange={(e) => setShowPassword(e.target.checked)}
						/>
						Show password
					</label>
				</div>
				<span className="setting-description">A strong password has been suggested. You may override it.</span>
			</div>
		</div>
	);
}

function StepTwoGitHubIntegration({
	state,
	updateField,
	onVerifyToken,
	loading,
}: {
	state: WizardState;
	updateField: <K extends keyof WizardState>(key: K, value: WizardState[K]) => void;
	onVerifyToken: () => Promise<void>;
	loading: boolean;
}): React.ReactElement {
	return (
		<div className="onboarding-form">
			<div className="form-group">
				<label htmlFor="github_token">GitHub PAT (Personal Access Token)</label>
				<div style={{ display: "flex", gap: "0.5rem" }}>
					<input
						id="github_token"
						type="password"
						value={state.githubToken}
						onChange={(e) => {
							updateField("githubToken", e.target.value);
							updateField("githubUsernameConfirmed", false);
							updateField("githubUsername", "");
						}}
						placeholder="ghp_..."
						required
						style={{ flex: 1 }}
					/>
					<button
						type="button"
						className="action-btn"
						style={{ background: "var(--blue)", color: "#000", whiteSpace: "nowrap" }}
						onClick={onVerifyToken}
						disabled={loading || !state.githubToken.trim()}
					>
						{loading ? "Verifying..." : "Verify"}
					</button>
				</div>
				<span className="setting-description">Personal access token with repo and issues scope</span>
			</div>

			{state.githubUsernameConfirmed && (
				<div className="form-group">
					<label htmlFor="github_username">GitHub Username</label>
					<input
						id="github_username"
						type="text"
						value={state.githubUsername}
						onChange={(e) => updateField("githubUsername", e.target.value)}
						placeholder="username"
						required
					/>
					<span className="setting-description">Inferred from your token. Confirm or edit if needed.</span>
				</div>
			)}
		</div>
	);
}

function StepThreeEventMode({
	state,
	updateField,
}: {
	state: WizardState;
	updateField: <K extends keyof WizardState>(key: K, value: WizardState[K]) => void;
}): React.ReactElement {
	const mode = state.githubEventMode;
	const showPollInterval = isPollingMode(mode);
	const intervalError =
		showPollInterval && state.githubPollIntervalMs.trim().length > 0
			? parsePollIntervalMs(state.githubPollIntervalMs) === null
				? `Polling interval must be a whole number of at least ${MIN_POLL_INTERVAL_MS} ms.`
				: null
			: null;

	return (
		<div className="onboarding-form">
			<div className="form-group">
				<span className="setting-description">Choose how TARS discovers GitHub events.</span>
				<div style={{ display: "flex", flexDirection: "column", gap: "0.5rem", marginTop: "0.5rem" }}>
					{EVENT_MODE_OPTIONS.map((option) => (
						<label
							key={option}
							style={{ display: "flex", alignItems: "center", gap: "0.5rem", cursor: "pointer", fontSize: "0.95rem" }}
						>
							<input
								type="radio"
								name="github_event_mode"
								value={option}
								checked={mode === option}
								onChange={() => {
									updateField("githubEventMode", option);
									if (isPollingMode(option) && !state.githubPollIntervalMs.trim()) {
										updateField("githubPollIntervalMs", String(DEFAULT_POLL_INTERVAL_MS));
									}
								}}
							/>
							<span>{option === "webhook" ? "Webhook" : option === "polling" ? "Polling" : "Both"}</span>
						</label>
					))}
				</div>
			</div>

			{showPollInterval && (
				<div className="form-group">
					<label htmlFor="github_poll_interval_ms">Polling Interval (ms)</label>
					<input
						id="github_poll_interval_ms"
						type="number"
						min={MIN_POLL_INTERVAL_MS}
						step={1000}
						value={state.githubPollIntervalMs}
						onChange={(e) => updateField("githubPollIntervalMs", e.target.value)}
						placeholder={`at least ${MIN_POLL_INTERVAL_MS}`}
						required
					/>
					<span className="setting-description">
						Positive integer in milliseconds. Minimum {MIN_POLL_INTERVAL_MS} ms.
					</span>
					{intervalError && (
						<span style={{ color: "var(--red)", fontSize: "0.8125rem" }}>{intervalError}</span>
					)}
			</div>
		)}
		{mode === "webhook" && (
			<p className="setting-description">No polling interval is required for webhook-only mode.</p>
		)}
	</div>
	);
}

function StepFourWebhookSecurity({
	state,
	updateField,
	onGenerateSecret,
	loading,
}: {
	state: WizardState;
	updateField: <K extends keyof WizardState>(key: K, value: WizardState[K]) => void;
	onGenerateSecret: () => Promise<void>;
	loading: boolean;
}): React.ReactElement {
	const [showSecret, setShowSecret] = useState(true);

	return (
		<div className="onboarding-form">
			<div className="form-group">
				<label htmlFor="webhook_secret">Webhook Secret</label>
				<div style={{ display: "flex", gap: "0.5rem" }}>
					<input
						id="webhook_secret"
						type={showSecret ? "text" : "password"}
						value={state.webhookSecret}
						onChange={(e) => updateField("webhookSecret", e.target.value)}
						placeholder="Generate a secret..."
						required
						style={{ flex: 1 }}
					/>
					<button
						type="button"
						className="action-btn"
						style={{ background: "var(--yellow)", color: "#000", whiteSpace: "nowrap" }}
						onClick={onGenerateSecret}
						disabled={loading}
					>
						{loading ? "Generating..." : "Regenerate"}
					</button>
				</div>
				<div style={{ display: "flex", alignItems: "center", gap: "0.5rem", marginTop: "0.35rem" }}>
					<label style={{ display: "flex", alignItems: "center", gap: "0.4rem", cursor: "pointer", fontSize: "0.875rem", color: "var(--muted)" }}>
						<input
							type="checkbox"
							checked={showSecret}
							onChange={(e) => setShowSecret(e.target.checked)}
						/>
						Show secret
					</label>
				</div>
				<span className="setting-description">Used to verify GitHub webhook signatures.</span>
			</div>

			{state.webhookSecret.length > 0 && (
				<div
					style={{
						background: "var(--bg)",
						border: "1px solid var(--border)",
						borderRadius: "6px",
						padding: "1rem",
						fontSize: "0.875rem",
						lineHeight: 1.6,
					}}
				>
					<strong>How to configure this secret in GitHub:</strong>
					<ol style={{ marginLeft: "1.25rem", marginTop: "0.5rem" }}>
						<li>Go to your repository on GitHub.</li>
						<li>Click <strong>Settings</strong> then <strong>Webhooks</strong>.</li>
						<li>Click <strong>Add webhook</strong>.</li>
						<li>Set <strong>Payload URL</strong> to your TARS webhook endpoint.</li>
						<li>Paste the secret above into <strong>Secret</strong>.</li>
						<li>Select <strong>Let me select individual events</strong> and enable <strong>Issues</strong> and <strong>Issue comments</strong>.</li>
						<li>Click <strong>Add webhook</strong>.</li>
					</ol>
					<div style={{ marginTop: "0.75rem" }}>
						<label style={{ display: "flex", alignItems: "center", gap: "0.5rem", cursor: "pointer" }}>
							<input
								type="checkbox"
								checked={state.webhookSecretConfirmed}
								onChange={(e) => updateField("webhookSecretConfirmed", e.target.checked)}
							/>
							<span>I have configured the webhook secret in my GitHub repository settings.</span>
						</label>
					</div>
				</div>
			)}
		</div>
	);
}

function StepFiveWorkspaceInit({
	state,
	onFetchRepos,
	onToggleRepo,
	onSetAllReposSelected,
	onFinish,
	loading,
}: {
	state: WizardState;
	onFetchRepos: () => Promise<void>;
	onToggleRepo: (index: number) => void;
	onSetAllReposSelected: (selected: boolean) => void;
	onFinish: () => Promise<void>;
	loading: boolean;
}): React.ReactElement {
	const selectedCount = state.repositories.filter((r) => r.selected).length;

	return (
		<div className="onboarding-form">
			<div style={{ display: "flex", gap: "0.5rem", alignItems: "center" }}>
				<button
					type="button"
					className="action-btn"
					style={{ background: "var(--blue)", color: "#000" }}
					onClick={onFetchRepos}
					disabled={loading || !state.githubToken.trim()}
				>
					{loading && state.repositories.length === 0 ? "Fetching..." : "Fetch Repositories"}
				</button>
				<span style={{ color: "var(--muted)", fontSize: "0.875rem" }}>
					{selectedCount > 0 && `${selectedCount} selected`}
				</span>
			</div>

			{state.repositories.length > 0 && (
				<div
					style={{
						background: "var(--bg)",
						border: "1px solid var(--border)",
						borderRadius: "6px",
						padding: "1rem",
							maxHeight: "16rem",
							overflowY: "auto",
						}}
					>
						<div style={{ display: "flex", flexDirection: "column", gap: "0.5rem" }}>
							<div style={{ display: "flex", alignItems: "center", gap: "0.5rem", marginBottom: "0.25rem" }}>
								<button
									type="button"
									className="action-btn"
									style={{
										background: "var(--surface)",
										border: "1px solid var(--border)",
										color: "var(--text)",
										fontSize: "0.75rem",
										padding: "0.25rem 0.5rem",
									}}
									onClick={() => onSetAllReposSelected(!state.repositories.every((r) => r.selected))}
								>
									{state.repositories.every((r) => r.selected) ? "Deselect All" : "Select All"}
								</button>
							</div>
						{state.repositories.map((repo, i) => (
							<label
								key={repo.fullName}
								style={{
									display: "flex",
									alignItems: "center",
									gap: "0.5rem",
									cursor: "pointer",
									padding: "0.35rem 0",
									borderBottom: "1px solid var(--border)",
								}}
							>
								<input
									type="checkbox"
									checked={repo.selected}
									onChange={() => onToggleRepo(i)}
								/>
								<span style={{ fontSize: "0.875rem" }}>{repo.fullName}</span>
							</label>
						))}
					</div>
				</div>
			)}
		</div>
	);
}
