import React, { useCallback, useEffect, useMemo, useRef, useState } from "react";
import {
	submitOnboarding,
	verifyGitHubToken,
	generateWebhookSecret,
	listAccessibleRepositories,
	initializeWorkspaces,
	fetchOnboardingConfig,
} from "../../api/onboarding.js";
import { isWebhookMode } from "../../../domain/onboarding/policy.js";
import {
	STORAGE_KEY,
	TOTAL_STEPS,
	buildInitialState,
	generatePassword,
	getDefaultState,
	mergeAccessibleRepos,
	saveState,
	type WizardState,
} from "./wizard-state.js";
import {
	isAiLlmStepValid,
	isEventModeStepValid,
} from "./wizard-validation.js";
import { buildOnboardingBody } from "./wizard-submission.js";
import { StepOneAdminCredentials } from "./steps/StepOneAdminCredentials.js";
import { StepTwoGitHubIntegration } from "./steps/StepTwoGitHubIntegration.js";
import { StepThreeEventMode } from "./steps/StepThreeEventMode.js";
import { StepFourAiLlm } from "./steps/StepFourAiLlm.js";
import { StepFiveWorkspaceInit } from "./steps/StepFiveWorkspaceInit.js";
import type { OnboardingConfig } from "../../api/onboarding.js";

// Re-exported for callers (tests and the admin entrypoint) that depend on the
// historical public surface of this module.
export { buildInitialState } from "./wizard-state.js";
export { isAiLlmStepValid } from "./wizard-validation.js";

function getStepSubtitle(step: number): string {
	switch (step) {
		case 1:
			return "Create the master admin account for the dashboard.";
		case 2:
			return "Connect your GitHub account with a Personal Access Token.";
		case 3:
			return "Choose how Yolomatic receives GitHub events by default.";
		case 4:
			return "Configure the AI / LLM provider, Ollama container, and model.";
		case 5:
			return "Initialize workspaces for the repositories you want Yolomatic to manage.";
		default:
			return "";
	}
}

export function OnboardingWizard({ onComplete }: { onComplete?: () => void }): React.ReactElement {
	const [state, setState] = useState<WizardState>(getDefaultState);
	const [configLoading, setConfigLoading] = useState(true);
	const [configError, setConfigError] = useState<string | null>(null);
	const [loading, setLoading] = useState(false);
	const [done, setDone] = useState(false);

	useEffect(() => {
		let cancelled = false;
		fetchOnboardingConfig()
			.then((config: OnboardingConfig) => {
				if (cancelled) return;
				setState(buildInitialState(config));
				setConfigLoading(false);
			})
			.catch((err) => {
				if (cancelled) return;
				setConfigError(err instanceof Error ? err.message : String(err));
				setState(buildInitialState(null));
				setConfigLoading(false);
			});
		return () => {
			cancelled = true;
		};
	}, []);

	useEffect(() => {
		if (!configLoading) saveState(state);
	}, [state, configLoading]);

	const setError = useCallback((error: string | null) => {
		setState((prev) => ({ ...prev, error }));
	}, []);

	const goToStep = useCallback((step: number) => {
		setState((prev) => ({ ...prev, step: Math.max(1, Math.min(TOTAL_STEPS, step)), error: null }));
	}, []);

	const updateField = useCallback(<K extends keyof WizardState>(key: K, value: WizardState[K]) => {
		setState((prev) => ({ ...prev, [key]: value, error: null }));
	}, []);

	const handleVerifyToken = useCallback(async () => {
		setLoading(true);
		setError(null);
		try {
			const result = await verifyGitHubToken(state.githubToken.trim());
			setState((prev) => ({ ...prev, githubUsername: result.username, githubUsernameConfirmed: true }));
		} catch (err) {
			setError(err instanceof Error ? err.message : String(err));
		} finally {
			setLoading(false);
		}
	}, [state.githubToken, setError]);

	const handleGenerateSecret = useCallback(async () => {
		setLoading(true);
		setError(null);
		try {
			const result = await generateWebhookSecret();
			setState((prev) => ({ ...prev, webhookSecret: result.secret }));
		} catch (err) {
			setError(err instanceof Error ? err.message : String(err));
		} finally {
			setLoading(false);
		}
	}, [setError]);

	const hasAutoGeneratedSecretRef = useRef(false);

	useEffect(() => {
		if (
			state.step === 3 &&
			isWebhookMode(state.githubEventMode) &&
			!state.webhookSecret &&
			!state.webhookSecretProtected &&
			!loading &&
			!hasAutoGeneratedSecretRef.current
		) {
			hasAutoGeneratedSecretRef.current = true;
			handleGenerateSecret();
		}
	}, [state.step, state.githubEventMode, state.webhookSecret, state.webhookSecretProtected, loading, handleGenerateSecret]);

	const handleFetchRepos = useCallback(async () => {
		setLoading(true);
		setError(null);
		try {
			const result = await listAccessibleRepositories(state.githubToken.trim());
			setState((prev) => ({
				...prev,
				repositories: mergeAccessibleRepos(
					result.repositories,
					result.configured ?? [],
					prev.repositories,
				),
			}));
		} catch (err) {
			setError(err instanceof Error ? err.message : String(err));
		} finally {
			setLoading(false);
		}
	}, [state.githubToken, setError]);

	const toggleRepo = useCallback((index: number) => {
		setState((prev) => {
			const repos = [...prev.repositories];
			repos[index] = { ...repos[index], selected: !repos[index].selected };
			return { ...prev, repositories: repos };
		});
	}, []);

	const setAllReposSelected = useCallback((selected: boolean) => {
		setState((prev) => ({
			...prev,
			repositories: prev.repositories.map((repo) => ({ ...repo, selected })),
		}));
	}, []);

	const hasAutoFetchedReposRef = useRef(false);

	useEffect(() => {
		// Auto-load the repository list when the operator reaches step 5 so they
		// do not have to click Fetch. Only runs once per mount and only when a
		// GitHub token is available (entered or already configured).
		const hasToken = state.githubToken.trim().length > 0 || state.githubTokenProtected;
		if (
			state.step === 5 &&
			hasToken &&
			state.repositories.length === 0 &&
			!loading &&
			!hasAutoFetchedReposRef.current
		) {
			hasAutoFetchedReposRef.current = true;
			void handleFetchRepos();
		}
	}, [state.step, state.githubToken, state.githubTokenProtected, state.repositories, loading, handleFetchRepos]);

	const handleFinish = useCallback(async () => {
		setLoading(true);
		setError(null);
		try {
			const selectedRepos = state.repositories.filter((r) => r.selected);
			const canInitWorkspaces = state.githubToken.trim().length > 0 || state.githubTokenProtected;
			if (canInitWorkspaces && selectedRepos.length > 0) {
				await initializeWorkspaces({
					token: state.githubToken.trim(),
					username: state.githubUsername.trim(),
					repos: selectedRepos.map((r) => ({ owner: r.owner, repo: r.repo })),
				});
			}

			await submitOnboarding(buildOnboardingBody(state));

			localStorage.removeItem(STORAGE_KEY);
			setDone(true);
			onComplete?.();
		} catch (err) {
			setError(err instanceof Error ? err.message : String(err));
			setLoading(false);
		}
	}, [state, onComplete]);

	const handleCancel = useCallback(() => {
		if (confirm("Are you sure you want to cancel the onboarding? Your progress will be lost.")) {
			localStorage.removeItem(STORAGE_KEY);
			window.location.reload();
		}
	}, []);

	const canGoNext = useMemo(() => {
		switch (state.step) {
			case 1:
				return state.adminFullName.trim().length > 0 && state.adminUsername.trim().length > 0 && (state.adminPasswordProtected || state.adminPassword.trim().length > 0);
			case 2:
				return (state.githubTokenProtected || state.githubToken.trim().length > 0) && state.githubUsernameConfirmed;
			case 3:
				return isEventModeStepValid(state.githubEventMode, state.githubPollIntervalMs, state.webhookSecret, state.webhookSecretProtected);
			case 4:
				return isAiLlmStepValid(state.piAgentProvider, state.piAgentModel, state.ollamaContainerName);
			case 5:
				return true;
			default:
				return false;
		}
	}, [state]);

	if (configLoading) {
		return (
			<div className="onboarding-screen">
				<div className="onboarding-card">
					<h2>Loading configuration…</h2>
					<p className="onboarding-subtitle">
						Loading your current onboarding settings.
					</p>
				</div>
			</div>
		);
	}

	if (done) {
		return (
			<div className="onboarding-screen">
				<div className="onboarding-card">
					<h2>Setup Complete</h2>
					<p className="onboarding-subtitle">
						Your settings have been saved and Yolomatic is loading them now.
					</p>
				</div>
			</div>
		);
	}

	return (
		<div className="onboarding-screen">
			<div className="onboarding-card">
				<div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: "0.5rem" }}>
					<h1>Welcome to Yolomatic</h1>
					<span style={{ color: "var(--muted)", fontSize: "0.875rem" }}>Step {state.step} of {TOTAL_STEPS}</span>
				</div>
				<div
					style={{
						display: "flex",
						gap: "0.25rem",
						marginBottom: "1.5rem",
					}}
				>
					{Array.from({ length: TOTAL_STEPS }, (_, i) => (
						<div
							key={i}
							style={{
								flex: 1,
								height: "4px",
								borderRadius: "2px",
								background: i < state.step ? "var(--blue)" : "var(--border)",
								transition: "background 0.2s ease",
							}}
						/>
					))}
				</div>
				<p className="onboarding-subtitle">{getStepSubtitle(state.step)}</p>

				{configError && (
				<div className="error-banner" style={{ background: "var(--yellow)" }}>
					Could not load current configuration ({configError}). Showing defaults.
				</div>
			)}
			{state.error && <div className="error-banner">{state.error}</div>}

				{state.step === 1 && (
					<StepOneAdminCredentials
						state={state}
						updateField={updateField}
						onGeneratePassword={() => updateField("adminPassword", generatePassword())}
					/>
				)}
				{state.step === 2 && (
					<StepTwoGitHubIntegration
						state={state}
						updateField={updateField}
						onVerifyToken={handleVerifyToken}
						loading={loading}
					/>
				)}
				{state.step === 3 && (
					<StepThreeEventMode
						state={state}
						updateField={updateField}
						onGenerateSecret={handleGenerateSecret}
						loading={loading}
					/>
				)}
				{state.step === 4 && (
					<StepFourAiLlm
						state={state}
						updateField={updateField}
					/>
				)}
				{state.step === 5 && (
					<StepFiveWorkspaceInit
						state={state}
						onFetchRepos={handleFetchRepos}
						onToggleRepo={toggleRepo}
						onSetAllReposSelected={setAllReposSelected}
						loading={loading}
					/>
				)}

				<div style={{ display: "flex", gap: "0.75rem", marginTop: "1.5rem", justifyContent: "space-between" }}>
					<div style={{ display: "flex", gap: "0.75rem" }}>
						{state.step > 1 && (
							<button
								className="action-btn"
								style={{ background: "var(--surface)", border: "1px solid var(--border)", color: "var(--text)" }}
								type="button"
								onClick={() => goToStep(state.step - 1)}
								disabled={loading}
							>
								Back
							</button>
						)}
						<button
							className="action-btn"
							style={{ background: "var(--surface)", border: "1px solid var(--border)", color: "var(--red)" }}
							type="button"
								onClick={handleCancel}
								disabled={loading}
							>
							Cancel
						</button>
					</div>
					{state.step < TOTAL_STEPS ? (
						<button
							className="action-btn restart"
							type="button"
							onClick={() => goToStep(state.step + 1)}
							disabled={!canGoNext || loading}
						>
							Next
						</button>
					) : (
						<button
							className="action-btn restart"
							type="button"
							onClick={handleFinish}
							disabled={!canGoNext || loading}
						>
							{loading ? "Initializing..." : "Initialize & Finish"}
						</button>
					)}
				</div>
			</div>
		</div>
	);
}